STC\BannerBundle\Entity\Banner:
  type: entity
  repositoryClass:  STC\BannerBundle\Repository\BannerRepository
  table: banners
  gedmo:
    loggable: true
  id:
    id:
      type: integer
      generator: { strategy: auto }
  fields:
    name: 
      type: string
      nullable: true
      gedmo:
        - versioned
    client:
      type: string
      gedmo:
        - versioned        
    start_date:
    
      type: date
      gedmo:
        - versioned
    duration:
      type: integer
    enabled:
      type: boolean
    url:
      type: string
      gedmo:
        - versioned
      nullable: true

    created:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updated:
      type: datetime
      gedmo:
        timestampable:
          on: update
    status: # 0 - To validate,1 - Online, 2 - Offline
      type: integer
      nullable: true   
    last_version: 
      type: integer
      nullable: true              
  oneToOne:
    media:
      targetEntity: Application\Sonata\MediaBundle\Entity\Media
      cascade: ["persist"]
      joinColumn:
        name: media_id
        referencedColumnName: id
        nullable: true
      gedmo:
        - versioned
  manyToOne:   
    banner_type:
  
      targetEntity: BannerType
      inversedBy: banners
      joinColumn:
        name: banner_type_id
        referencedColumnName: id
        nullable: true
