home:
    pattern:  /
    defaults: { _controller: STCSiteBundle:Site:home }

whoWeAre:
    pattern:  /who-we-are
    defaults: { _controller: STCSiteBundle:Site:whoWeAre }

copyright:
    pattern:  /copyright
    defaults: { _controller: STCSiteBundle:Site:copyright }

allRightsReserved:
    pattern:  /all-rights-reserved
    defaults: { _controller: STCSiteBundle:Site:allRightsReserved }
