parameters:
    menu_builder.class: STC\SiteBundle\Menu\MenuBuilder

services:
    # the menu builder service. Can be used for several menus
    main.menu_builder:
        class: %menu_builder.class%
        arguments: ["@knp_menu.factory","@translator","@service_container"]

    stc.main.menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

    site.socialBarHelper:
        class : STC\SiteBundle\Helper\SocialBarHelper
        tags :
            - {name : 'templating.helper', alias : 'social-buttons'}
        arguments : [ @templating ]

    twig.extension.acme_social_bar:
        class: STC\SiteBundle\Twig\Extensions\TwigSocialBar
        tags:
            - { name: 'twig.extension' }
        arguments : [ @service_container ]